---
title: "12-Multivariante"
author: "Javier Trujillo"
date: "11/5/2021"
output: html_document
---

# Tablas de datos multidimensionales

## Ejemplo con tres dimensiones

```{r}
ans= sample(c("Si","No"), size=100, replace = TRUE)
sex = sample(c("H", "M"), size=100, replace = TRUE)
place = sample(c("San Francisco", "Barcelona", "Valencia", "Cobija", "Asturias"), size=100, replace= TRUE)

table(sex, ans, place)

ftable(sex, ans, place) #Une todas las tablas en una

ftable(sex, ans, place, col.vars = c("sex","ans")) # Más fácil de leer
```

La tabla queda separada en 5 tablas bidimensionales.


### Filtrar las tablas:

```{r}

table(sex, ans, place)["M","Si", "San Francisco"]
table(sex,ans, place)[,"Si", "Valencia"]
table(sex,ans, place)[,"No",]
table(sex,ans, place)["M", , "Cobija"]

```


### Frecuencias relativas
```{r}
prop.table(table (sex, ans, place)) #Frec. rel. globales
prop.table(table(sex, ans, place), margin = 3) #Frec. Rel.Marginal por lugar
prop.table(table(sex, ans, place), margin = c(1,3)) #Frec. Rel. Marginal por sexo y lugar


# Tabla plana de frecuencias (flat table)

ftable(prop.table(table (sex, ans, place)))

# El parámetro col.vars permite, con una concatenación, seleccionar las variables que servirán de columnas en la flat table
```





